<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MQTTHistorianWorker-9db6ca13-bd95-4b88-896e-058b92aecfe5</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.13" />
		<PackageReference Include="MQTTnet" Version="5.2.0.1603" />
	</ItemGroup>
</Project>
